using Pkg

# Build the documentation
cd("docs")
Pkg.activate(".")
Pkg.instantiate()

make_path = joinpath(@__DIR__, "docs/make.jl")
include(make_path)

# Path to the index.html file generated by Documenter
index_path = joinpath("build", "index.html")

# Check if the file exists before trying to open it
if isfile(index_path)
    run(`firefox $(index_path)`)
else
    println("Documentation build failed or index.html file not found.")
end