"""
    get_bandgap(Es::Array{Float64, 2}, kvalmax::Int64; printit::Bool=false) -> Float64

Calculate the bandgap from the given energy values.

# Arguments
- `Es::Array{Float64, 2}`: A 2D array of energy values where rows correspond to different k-points and columns correspond to different energy bands.
- `kvalmax::Int64`: The index of the highest occupied energy band (valence band maximum).
- `printit::Bool=true`: A boolean flag to control whether the bandgap value should be printed. Default is `true`.

# Returns
- `ΔE::Float64`: The calculated bandgap energy.
"""
function get_bandgap(Es, kvalmax::Int64; printit=false)
    valmax = maximum(Es[kvalmax, :])
    condmin = minimum(Es[kvalmax+1, :])
    ΔE = condmin - valmax
    if printit; @show ΔE; end 
    return ΔE
end

"""
    get_bandgap(file::AbstractString; printit::Bool=false) -> Float64

Calculate the bandgap from the EIGENVAL file.

# Arguments
- `file::AbstractString`: The path to the `EIGENVAL` file generated by VASP.
- `printit::Bool=true`: A boolean flag to control whether the bandgap value should be printed. Default is `true`.

# Returns
- `ΔE::Float64`: The calculated bandgap energy.
"""
function get_bandgap(file::AbstractString; printit=false)
    _, Es, occs = read_eigenval(file)
    VBM, CBM, _ = get_vbm_and_cbm(Es, occs)
    ΔE = CBM - VBM
    if printit; @show ΔE; end
    return ΔE
end

"""
    get_vbm_and_cbm(Es::Array{Float64, 2}, occs::Array{Float64, 2}; occ_threshold::Float64=0.9, printit::Bool=false) -> Tuple{Float64, Float64, Tuple{Int64, Int64}}

Determine the valence band maximum (VBM) and conduction band minimum (CBM) from energy values and occupations.

# Arguments
- `Es::Array{Float64, 2}`: A 2D array of energy values where rows correspond to different energy bands and columns correspond to different k-points.
- `occs::Array{Float64, 2}`: A 2D array of occupation values corresponding to the energy values in `Es`.
- `occ_threshold::Float64=0.9`: The occupation threshold to distinguish between occupied and unoccupied bands. Default is `0.9`.

# Returns
- `VBM::Float64`: The valence band maximum energy.
- `CBM::Float64`: The conduction band minimum energy.
- `VBM_Index::Tuple{Int64, Int64}`: A tuple containing the band index and k-point index of the VBM.
"""
function get_vbm_and_cbm(Es, occs; occ_threshold=0.9, printit=false)
    val_maxs = Float64[]
    cond_mins = Float64[]
    vbm_indices = Int64[]
    for (k, band_occ) in enumerate(eachcol(occs))
        occupied_bands = filter(x->x>occ_threshold, band_occ)
        vbm_index = length(occupied_bands)
        push!(vbm_indices, vbm_index)
        push!(val_maxs, Es[vbm_index, k])
        push!(cond_mins, Es[vbm_index+1, k])
    end
    _, vbm_k_index = findmax(val_maxs)
    vbm_index = vbm_indices[vbm_k_index]
    vbm = maximum(val_maxs)
    cbm = minimum(cond_mins)
    if printit; @show (vbm, cbm); end
    return vbm, cbm, (vbm_index, vbm_k_index)
end


"""
    get_fermi_level(Es, occ; occ_threshold=0.9, printit::Bool=false)

Calculate the Fermi level of a system given the energy levels and their corresponding occupancies.

# Arguments
- `Es::Array{Float64, 2}`: A 2D array of energy values where rows correspond to different energy bands and columns correspond to different k-points.
- `occs::Array{Float64, 2}`: A 2D array of occupation values corresponding to the energy values in `Es`.
- `occ_threshold::Float64=0.9`: The occupation threshold to distinguish between occupied and unoccupied bands. Default is `0.9`.

# Returns
- `E_fermi::Float64`: Fermi energy for semiconductor
"""
function get_fermi_energy(Es, occ; occ_threshold=0.9, printit=false)
    println(printit)
    vbm, cbm, _ = get_vbm_and_cbm(Es, occ; occ_threshold)
    E_fermi = cbm - abs(cbm - vbm) * 0.5
    if printit; @show E_fermi; end
    return E_fermi
end