"""
    read_value_from_outcar(param, file; mode="first", type=Float64, N=1)

Read values associated with a parameter from a file.

# Arguments
- `param::AbstractString`: The parameter to search for in the file.
- `file::AbstractString`: The path to the file to read from.
- `mode::AbstractString`: Determines whether to extract the "first" or "last" occurrence of the value in the line. Defaults to "first".
- `type::Type`: The data type to which the values should be converted. Defaults to `Float64`.

# Returns
- `param_values::Vector{type}`: A vector of values of the specified type associated with the parameter found in the file.

# Description
This function reads a file line-by-line and searches for lines containing the specified parameter `param`. 
It extracts the values associated with the parameter from each line, converts them to the specified `type`, and collects them in a vector.
"""
function read_value_from_outcar(param, file; type=Float64, line_mode="first")::Vector
    #lines = open_and_read(file)
    param_values = type[]
    for line in eachline(file)
        if occursin(param, line)

            # Replace some symbols with space
            line_ = line
            for special_char in [':', '=']
                line_ = replace(line_, special_char => ' ')
            end

            # Split the line at param
            line_split = split_line(line_, char=param)

             # only consider occurences where param is not at the end of the line
            if length(line_split) > 1
                line_after_param = split_line(line_, char=param)[2]

                line_elements_of_type = filter(x->x≠nothing, tryparse.(type, split_line(line_after_param)))

                if line_mode == "first" && length(line_elements_of_type) > 0
                    push!(param_values, line_elements_of_type[1])
                elseif line_mode == "last" && length(line_elements_of_type) > 0
                    push!(param_values, line_elements_of_type[end])
                end
            end
        end
    end
    if length(param_values) == 0
        throw("No value for parameter $param found.")
    else
        return param_values
    end
end

"""
    read_eigenvalues_from_outcar(file; line_jump=6)

Reads k-points, energy eigenvalues, and band occupations from an OUTCAR file generated by VASP, extracting the necessary data across multiple configurations.

# Arguments
- `file::String`: Path to the OUTCAR file to read.
- `line_jump::Int`: Number of lines to skip after encountering the "E-fermi" keyword to reach the first energy eigenvalue (default: 6).

# Returns
- `kpoints::Matrix{Float64}`: A matrix of k-points (3xNk), where `Nk` is the number of k-points.
- `eigenvalues::Array{Float64, 3}`: A 3D array of energy eigenvalues (Nbands x Nk x Nconfig), where `Nbands` is the number of bands and `Nconfig` is the number of configurations.
- `occupations::Array{Float64, 3}`: A 3D array of band occupations (Nbands x Nk x Nconfig).
"""
function read_eigenvalues_from_outcar(file; line_jump=6)
    lines = open_and_read(file)
    lines = split_lines(lines)
    l = 1; nbands = 0; nconfig = 0; nkpts = 0
    kp = Vector{Float64}[]
    Es_all = Matrix{Float64}[]
    occs_all = Matrix{Float64}[]
    @views while l < length(lines)
        # every new configuration starts with a line that contains E-fermi
        if "E-fermi" ∉ lines[l]
            l += 1
        else
            found_config = true 
            Es_config = Vector{Float64}[]
            occs_config = Vector{Float64}[]
            # jump `line_jump` lines ahead to the first energy eigenvalue
            nconfig += 1; l += line_jump
            k⃗ = parse.(Float64, lines[l-2][end-2:end])
            if length(kp) ≠ nkpts || nkpts == 0; push!(kp, k⃗); end
            while found_config
                empty_count = 0
                Es_k = Float64[]
                occ_k = Float64[]

                while !isempty(lines[l])
                    if "k-point" in lines[l]
                        k⃗ = parse.(Float64, lines[l][end-2:end])
                        if length(kp) ≠ nkpts; push!(kp, k⃗); end
                        l += 2
                    end
                    values = parse.(Float64, lines[l])
                    push!(Es_k, values[2])
                    push!(occ_k, values[3])
                    l += 1
                end
                push!(Es_config, Es_k)
                push!(occs_config, occ_k)
                nbands = length(Es_k)
                # increase empty_count by one from previous k-point and check if next line is also empty
                empty_count += 1; l += 1; if isempty(lines[l]); empty_count += 1; end
                # data for one configuration ends with two consecutive empty lines
                if empty_count == 2; found_config = false; end
            end
            nkpts = length(Es_config)
            # reshape energy eigenvalues in to shape (nbands, nkpts)
            Es = zeros(nbands, nkpts)
            occs = zeros(nbands, nkpts)
            for k in 1:nkpts, i in 1:nbands
                Es[i, k] = Es_config[k][i]
                occs[i, k] = occs_config[k][i]
            end
            push!(Es_all, Es)
            push!(occs_all, occs)
        end
    end
    return cat(kp..., dims=2), cat(Es_all..., dims=3), cat(occs_all..., dims=3)
end

"""
    read_forces_from_outcar(file)

Reads the atomic forces and positions from a VASP OUTCAR file.

# Arguments
- `file::String`: The path to the VASP OUTCAR file from which to read the forces and positions.

# Returns
- `positions::Array{Float64, 3}`: A 3D array (3 × N_ions × N_configs).
- `forces::Array{Float64, 3}`: A 3D array (3 × N_ions × N_configs).
"""
function read_forces_from_outcar(file)
    lines = open_and_read(file)
    n_ions = Int(read_value_from_outcar("NIONS", file, type=Int64)[1])
    forces = Float64[]  # Store the forces for all ions
    positions = Float64[]

    recording = false
    found_configs = 0
    counted_ions = 0
    l = 1
    while l ≤ length(lines)
        line = lines[l]
        if occursin("TOTAL-FORCE", line)
            recording = true
            found_configs += 1
            l += 1
        elseif recording && counted_ions == n_ions
            recording = false
            counted_ions = 0
        elseif recording
            values = parse.(Float64, split_line(line))
            append!(positions, values[1:3])
            append!(forces, values[4:6])
            counted_ions += 1
        end
        l += 1
    end
    return reshape(positions, 3, n_ions, found_configs), reshape(forces, 3, n_ions, found_configs)
end